apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-dep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webcon
          image: pranaygupta1988/website-app:27
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            requests:
              memory: "32Mi"
              cpu: "100m"
            limits:
              memory: "64Mi"
              cpu: "200m"

---

apiVersion: v1
kind: Service
metadata:
  name: webapp-ser
spec:
  selector: 
    app: webapp
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32208
      protocol: TCP




















